### ISSUE TITLE
Self-tests fail via cpanm when installing on Perl 5.8.8 (CentOS 5)

### ISSUE THREAD

**Issue by wyoung** [xslate/p5-Text-Xslate#145]
The following complaints prevent Text::Xslate from installing via `cpanm` on CentOS 5 unless you say `--force`:

    t/900_bugs/039_issue96.t ........................ ok
    "remove_tree" is not exported by the File::Path module
    Can't continue after import errors at t/900_bugs/040_issue95.t line 6.
    BEGIN failed--compilation aborted at t/900_bugs/040_issue95.t line 6.
    t/900_bugs/040_issue95.t ........................
    Dubious, test returned 255 (wstat 65280, 0xff00)
    No subtests run
    t/900_bugs/041_cachedir_other_process.t ......... ok
    Text::Xslate: Iterating data must be an ARRAY reference, not 3 (<string>:2) at t
    /900_bugs/042_perl59_issue.t line 13.
    ----------------------------------------------------------------------------
    : '/' ~ uri('a')
    : for 3 -> $n { }
    ----------------------------------------------------------------------------

It appears to run correctly if you force the install, and prior versions have been working for us flawlessly on CentOS 5 for over a year now.

We'd rather not roll back to a prior version of Text::Xslate to get around this. It would be better if the distribution maintained compatibility with Perl 5.8 for a white longer, since it will still be in use for some time yet, and not just by us. RHEL 5 (which ships Perl 5.8.8) will still be in mainstream support [for another year and a half](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Product_life_cycle). There are other pressures keeping Perl 5.8 relevant, too.

**Comment by syohex** [comment]
I have fixed this issue. Please wait next release.

**Comment by syohex** [comment]
I have release version 3.3.7. Please check it. And thanks for reporting.

https://metacpan.org/release/SYOHEX/Text-Xslate-3.3.7

**Comment by wyoung** [comment]
Thanks! I've installed the new version successfully on CentOS 5, Ubuntu 8.04 LTS (also uses Perl 5.8.8), OS X Yosemite, Ubuntu LTS 14.04, and CentOS 7.
