### ISSUE TITLE
Needs to divide PP module from Text::Xslate

### ISSUE THREAD

**Issue by worthmine** [xslate/p5-Text-Xslate#212]
As you know, Text::Xslate is very useful module but it depends on XS.
I knew Text::Xslate::PP is included in this Package and tried to install it alone.

1. Actually, `cpanm Text::Xslate::PP` was transported to installing Text::Xslate.
2. And I have tried copying Text::Xslate::PP to my test environment, [it needs Text::Xslate::Utils](https://github.com/xslate/p5-Text-Xslate/blob/a7908ee382ed01f3a407fe826f2741de76287d36/lib/Text/Xslate/PP.pm#L12).
3. But [Text::Xslate::Utils requires Text::Xslate](https://github.com/xslate/p5-Text-Xslate/blob/a7908ee382ed01f3a407fe826f2741de76287d36/lib/Text/Xslate/Util.pm#L51), so Text::Xslate::PP itself requires Text::Xslate.
4. so it's a kind of loops

How Can I use just only Text::Xslate::PP?

**Comment by skaji** [comment]
You can try
```
cpanm --pureperl Text::Xslate
```

**Comment by worthmine** [comment]
Thank you for early reply!
